"""Add hidden column on response + make question hidden non-nullable

Revision ID: 0a1a4254a80a
Revises: 2ba5af5fae01
Create Date: 2021-04-30 13:16:42.301186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a1a4254a80a'
down_revision = '2ba5af5fae01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('question', 'hidden',
                    existing_type=sa.BOOLEAN(),
                    nullable=False)
    op.add_column('response', sa.Column('hidden', sa.Boolean(), nullable=True))
    op.execute("UPDATE response SET hidden = false")
    op.alter_column('response', 'hidden', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('response', 'hidden')
    op.alter_column('question', 'hidden',
                    existing_type=sa.BOOLEAN(),
                    nullable=True)
    # ### end Alembic commands ###
