"""add picture response

Revision ID: 0fbc5c9ccd33
Revises: 0a1a4254a80a
Create Date: 2021-05-02 15:27:04.476977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fbc5c9ccd33'
down_revision = '0a1a4254a80a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('picture', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question', 'picture')
    # ### end Alembic commands ###
