"""add ranking to responses

Revision ID: 2840882cf612
Revises: 322e24fbc745
Create Date: 2021-05-17 22:03:48.011718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2840882cf612'
down_revision = '322e24fbc745'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'question_response',
        sa.Column(
            'index',
            sa.Integer(),
            nullable=True))
    op.execute('COMMIT')
    op.execute('ALTER TYPE questionsubtype ADD VALUE \'RANKING\'')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question_response', 'index')
    # ### end Alembic commands ###
