"""add color to user

Revision ID: 2ba5af5fae01
Revises: 
Create Date: 2021-04-27 22:32:51.427333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ba5af5fae01'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('color', sa.String(length=128), nullable=True))
    op.execute("UPDATE users SET color = '#2962FF'")
    op.alter_column('users', 'color', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'color')
    # ### end Alembic commands ###
