"""add LYRICS response sub type

Revision ID: 4ca4afec99ef
Revises: 7e7bffaf9984
Create Date: 2021-06-13 14:30:48.310260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ca4afec99ef'
down_revision = '7e7bffaf9984'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('COMMIT')
    op.execute('ALTER TYPE questionsubtype ADD VALUE \'LYRICS\'')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
